### ISSUE TITLE
Error fetching dependencies

### ISSUE THREAD

**Issue by joerg-krause** [openhome/ohdevtools#2]
Using latest master commit b3d98ccf832ef67b80ef8261a3b59a339bd3bd19, fetching the dependencies fail with:

```
ohdevtools ) python2 go.py help fetch_dependencies
Command: fetch_dependencies

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/data/git/ohdevtools/commands/fetch_dependencies.py", line 6, in <module>
    from ci_build import default_platform
  File "ci_build.py", line 2, in <module>
    from dependencies import read_json_dependencies_from_filename
  File "dependencies.py", line 16, in <module>
    import aws
  File "aws.py", line 28, in <module>
    credsFile = urlopen('http://core.linn.co.uk/aws-credentials' )
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by rockfather** [comment]
Fixed by ohdevtools ver 107

**Comment by joerg-krause** [comment]
Thanks! There is still an issue when fetching the dependencies for ohPipeline:

```
ohPipeline ) ./go fetch --all

Fetching 'testharness'
  from AWS s3://linn-artifacts-public/artifacts/testharness/testharness-0.1.50.tar.gz
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-public/artifacts/testharness/testharness-0.1.50.tar.gz'
  unpacking to '/home/joerg/Development/git/oh/ohPipeline/dependencies/AnyPlatform'
OK

Fetching 'openssl'
  from AWS s3://linn-artifacts-public/artifacts/openssl/openssl-0.2.65-Linux-x64-Release.tar.bz2
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-public/artifacts/openssl/openssl-0.2.65-Linux-x64-Release.tar.bz2'
  unpacking to '/home/joerg/Development/git/oh/ohPipeline/dependencies/Linux-x64'
OK

Fetching 'hardware'
  from AWS s3://linn-artifacts-private/hardware/hardware-Core1-4.855.36595.tar.gz
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-private/hardware/hardware-Core1-4.855.36595.tar.gz'
  **** WARNING - failed to fetch http://core.linn.co.uk/~artifacts/artifacts/hardware/hardware-Core1-4.855.36595.tar.gz ****

Fetching 'ohNet'
  from AWS s3://linn-artifacts-public/artifacts/ohNet/ohNet-1.21.2999-Linux-x64-Release.tar.gz
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-public/artifacts/ohNet/ohNet-1.21.2999-Linux-x64-Release.tar.gz'
  unpacking to '/home/joerg/Development/git/oh/ohPipeline/dependencies/Linux-x64'
OK

Fetching 'FunctionalTest'
  from AWS s3://linn-artifacts-public/artifacts/FunctionalTest/FunctionalTest-0.0.1069.zip
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-public/artifacts/FunctionalTest/FunctionalTest-0.0.1069.zip'
  unpacking to '/home/joerg/Development/git/oh/ohPipeline/dependencies/AnyPlatform/FunctionalTest'
OK

Fetching 'ohWafHelpers'
  from AWS s3://linn-artifacts-public/artifacts/ohWafHelpers/ohWafHelpers-0.0.99.tar.gz
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-public/artifacts/ohWafHelpers/ohWafHelpers-0.0.99.tar.gz'
  unpacking to '/home/joerg/Development/git/oh/ohPipeline/dependencies/AnyPlatform'
OK

Fetching 'TestTones'
  from AWS s3://linn-artifacts-private/testtones/TestTones-1.9.zip
  from 'https://s3-eu-west-1.amazonaws.com/linn-artifacts-private/testtones/TestTones-1.9.zip'
  **** WARNING - failed to fetch http://core.linn.co.uk/~artifacts/artifacts/testtones/TestTones-1.9.zip ****
Failed to fetch some dependencies: hardware TestTones
Failed to load requested dependencies
```
